<script>
  import { onMount, tick } from 'svelte';
  import { jarvis, connectJarvis, disconnectJarvis, sendJarvisCommand } from '../stores/jarvis.js';
  import { ansiToHtml } from '../utils/ansi.js';
  import ChatInput from './ChatInput.svelte';

  let messageContainer = $state(null);

  const scrollToBottom = async () => {
    await tick();
    if (messageContainer) {
      messageContainer.scrollTop = messageContainer.scrollHeight;
    }
  };

  // Scroll to bottom when new messages arrive
  $effect(() => {
    if (jarvis.messages.length > 0) {
      scrollToBottom();
    }
  });

  onMount(() => {
    connectJarvis();
    return () => {
      disconnectJarvis();
    };
  });
</script>

<div class="jarvis-chat-container">
  <div class="chat-meta-bar">
    {#if jarvis.status === 'online'}
      <div class="meta-left">
        <span class="online-indicator"></span>
        <span class="meta-title">JARVIS AGENT</span>
      </div>
      <span class="pane-badge font-mono">Pane {jarvis.paneId}</span>
    {:else}
      <div class="meta-left">
        <span class="offline-indicator"></span>
        <span class="meta-title">JARVIS OFFLINE</span>
      </div>
      <span class="offline-reason">Start jarvis in tmux to connect</span>
    {/if}
  </div>

  <div class="chat-messages" bind:this={messageContainer}>
    {#if jarvis.messages.length === 0}
      <div class="welcome-container">
        <div class="jarvis-avatar">🧠</div>
        <h3>Jarvis Supervisor Agent</h3>
        <p class="welcome-desc">
          This panel acts as a web-based proxy console directly to the running JARVIS supervisor tmux pane.
        </p>
        <div class="help-box">
          <span class="help-title">💡 How to use:</span>
          <ul>
            <li>Type any prompt or request (e.g. "show agent status" or "explain plan progress").</li>
            <li>Commands are injected directly as standard keyboard input into the pane buffer.</li>
            <li>Output generated by JARVIS is captured and streamed back here in real-time.</li>
          </ul>
        </div>
      </div>
    {:else}
      {#each jarvis.messages as msg, idx}
        <div class="message-row" class:user-msg={msg.sender === 'user'} class:jarvis-msg={msg.sender === 'jarvis'}>
          <div class="msg-bubble animate-fade-in">
            <div class="msg-header">
              <span class="msg-sender">{msg.sender === 'user' ? 'You' : 'JARVIS Console'}</span>
              <span class="msg-time">{msg.timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })}</span>
            </div>
            <div class="msg-body">
              {#if msg.sender === 'user'}
                <p class="user-text">{msg.content}</p>
              {:else}
                <pre class="terminal-block">{@html ansiToHtml(msg.content)}</pre>
              {/if}
            </div>
          </div>
        </div>
      {/each}
    {/if}
  </div>

  <div class="chat-footer">
    <ChatInput 
      disabled={jarvis.status !== 'online'} 
      onsend={(cmd) => sendJarvisCommand(cmd)} 
    />
  </div>
</div>

<style>
  .jarvis-chat-container {
    display: flex;
    flex-direction: column;
    height: 100%;
    min-height: 0;
  }

  .chat-meta-bar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 12px 16px;
    background: rgba(0, 0, 0, 0.2);
    border-bottom: 1px solid var(--border-color);
    flex-shrink: 0;
  }

  .meta-left {
    display: flex;
    align-items: center;
    gap: 8px;
  }

  .meta-title {
    font-size: 0.8rem;
    font-weight: 700;
    color: #ffffff;
    letter-spacing: 0.5px;
  }

  .online-indicator {
    width: 8px;
    height: 8px;
    background: #00e5ff;
    border-radius: 50%;
    box-shadow: 0 0 8px #00e5ff;
  }

  .offline-indicator {
    width: 8px;
    height: 8px;
    background: #ff5252;
    border-radius: 50%;
  }

  .pane-badge {
    background: rgba(0, 229, 255, 0.1);
    color: var(--accent-cyan);
    border: 1px solid var(--border-color);
    padding: 1px 6px;
    border-radius: 4px;
    font-size: 0.75rem;
  }

  .offline-reason {
    font-size: 0.75rem;
    color: var(--text-muted);
  }

  .chat-messages {
    flex-grow: 1;
    overflow-y: auto;
    padding: 16px;
    display: flex;
    flex-direction: column;
    gap: 16px;
    min-height: 0;
  }

  .welcome-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 24px;
    text-align: center;
    color: var(--text-secondary);
    height: 100%;
    gap: 12px;
  }

  .jarvis-avatar {
    font-size: 3rem;
    background: rgba(0, 229, 255, 0.05);
    border: 1px solid var(--border-color);
    width: 70px;
    height: 70px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    box-shadow: var(--shadow-glow);
  }

  .welcome-container h3 {
    color: #ffffff;
    font-weight: 600;
  }

  .welcome-desc {
    font-size: 0.85rem;
    max-width: 320px;
    line-height: 1.4;
  }

  .help-box {
    margin-top: 12px;
    background: rgba(255, 255, 255, 0.02);
    border: 1px solid var(--border-color);
    border-radius: 8px;
    padding: 12px 16px;
    text-align: left;
    max-width: 380px;
  }

  .help-title {
    font-size: 0.8rem;
    font-weight: 600;
    color: #ffffff;
    display: block;
    margin-bottom: 6px;
  }

  .help-box ul {
    margin-left: 16px;
    font-size: 0.75rem;
    line-height: 1.5;
  }

  .message-row {
    display: flex;
    width: 100%;
  }

  .message-row.user-msg {
    justify-content: flex-end;
  }

  .message-row.jarvis-msg {
    justify-content: flex-start;
  }

  .msg-bubble {
    max-width: 85%;
    display: flex;
    flex-direction: column;
    gap: 6px;
  }

  .user-msg .msg-bubble {
    max-width: 70%;
  }

  .msg-header {
    display: flex;
    align-items: center;
    gap: 8px;
    font-size: 0.75rem;
    color: var(--text-muted);
  }

  .user-msg .msg-header {
    justify-content: flex-end;
  }

  .msg-sender {
    font-weight: 600;
  }

  .user-msg .msg-sender {
    color: var(--accent-blue);
  }

  .jarvis-msg .msg-sender {
    color: var(--accent-cyan);
  }

  .msg-body {
    border-radius: 8px;
    overflow: hidden;
  }

  .user-text {
    background: rgba(41, 121, 255, 0.15);
    border: 1px solid rgba(41, 121, 255, 0.3);
    color: #ffffff;
    padding: 10px 14px;
    border-radius: 12px 12px 0 12px;
    font-size: 0.85rem;
    line-height: 1.4;
    word-break: break-word;
  }

  .terminal-block {
    margin: 0;
    background: var(--terminal-bg);
    border: 1px solid var(--terminal-border);
    padding: 12px;
    border-radius: 0 12px 12px 12px;
    font-family: var(--font-mono);
    font-size: 0.75rem;
    line-height: 1.5;
    white-space: pre-wrap;
    word-break: break-all;
    color: #cbd5e1;
    box-shadow: inset 0 2px 8px rgba(0, 0, 0, 0.5);
  }

  .chat-footer {
    padding: 16px;
    border-top: 1px solid var(--border-color);
    background: rgba(0, 0, 0, 0.15);
    flex-shrink: 0;
  }
</style>
